  - name: enable nodejs 20 # Used command module because dnf module not support module enable
    ansible.builtin.command: dnf module enable nodejs:20 -y 

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: install npm dependencies
    community.general.npm:
      path: /app
